# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cf < Formula
  desc "The Common Fate CLI"
  homepage "https://commonfate.io/"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/cf/v1.7.0/cf_1.7.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1ee02d3765d86c88295d5e38c39db02441440153ef293d364201b6ef517f50bf"

      def install
        bin.install "cf"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/cf/v1.7.0/cf_1.7.0_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5d10add721987b5544717585e3c60c4182bca06b02c3766736093747036e73ff"

      def install
        bin.install "cf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/cf/v1.7.0/cf_1.7.0_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a5741ffbf6ad6f9b2eb99a5c97afc6d5be3852aa22c3d831b545572c40f346d4"

      def install
        bin.install "cf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/cf/v1.7.0/cf_1.7.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "dbb494c147b709d42e6d4401aa7a88474bbdd9073187317d74ae6b10ca1c5a58"

      def install
        bin.install "cf"
      end
    end
  end
end
