# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdk < Formula
  desc "The Common Fate Provider Development Kit"
  homepage "https://commonfate.io/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/pdk/v0.2.0/pdk_0.2.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d7d2d088d443f7e61c697e6954675fd7e1fb89dde412bdc09c8202ecf80024a0"

      def install
        bin.install "pdk"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/pdk/v0.2.0/pdk_0.2.0_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d1b310b5fa6925139cc8e13fc1113c17f6a182a9cfd8d61aaf0567a020df4909"

      def install
        bin.install "pdk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/pdk/v0.2.0/pdk_0.2.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "362e4d70b39f9a4181af6ecc1fdb15f33b9d2c40c3bcdd0b32aa9d257e91c7b2"

      def install
        bin.install "pdk"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/pdk/v0.2.0/pdk_0.2.0_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f50c5d1c4734a5d1129ff18276ffad39fce262cbe15d6574b068612ba3f406de"

      def install
        bin.install "pdk"
      end
    end
  end
end
