# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdk < Formula
  desc "The Common Fate Provider Development Kit"
  homepage "https://commonfate.io/"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/pdk/v0.3.0/pdk_0.3.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5a1daf1138fc9eda7941a5b06f4d6d53bd8592470060f9817991a10c58be2d33"

      def install
        bin.install "pdk"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/pdk/v0.3.0/pdk_0.3.0_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cec59292a20e9e4727af9b93f707c9be391fcd8ed9b2b8eea07a8858025bc5c6"

      def install
        bin.install "pdk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/pdk/v0.3.0/pdk_0.3.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f1d6e6dfc2181789a3442aa7b94ada64ba5553e9d843975961e73d63c81db38b"

      def install
        bin.install "pdk"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/pdk/v0.3.0/pdk_0.3.0_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e3a6a7f37d93be83e5651cfce4f0fea410c03da5850be5440efb88bab03613a0"

      def install
        bin.install "pdk"
      end
    end
  end
end
