# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdk < Formula
  desc "The Common Fate Provider Development Kit"
  homepage "https://commonfate.io/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/pdk/v0.1.1/pdk_0.1.1_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "71fa24983f46bb8773a866fefe5ef71d8947bfa8b0cf4a9a2edca0281a00aab7"

      def install
        bin.install "pdk"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/pdk/v0.1.1/pdk_0.1.1_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "940dbe33a6e2a0b5dbb3099a34235874095c10a4e0110650063869ca2cbd761f"

      def install
        bin.install "pdk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/pdk/v0.1.1/pdk_0.1.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cb9fe7d450f2e57999c5934e8ca64f189e48123a438bfb669c99aa3ced183aa5"

      def install
        bin.install "pdk"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/pdk/v0.1.1/pdk_0.1.1_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4df17d0b8cdd081179d3d48d99a53fd1d0739fb23e50bbe6f5338d64814d71be"

      def install
        bin.install "pdk"
      end
    end
  end
end
